baseURL = '/'
languageCode = 'en-us'
paginate = 5
title = 'iambear.one'
theme = "hugo-PaperMod"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
pygmentsUseClasses = true

[params]
env = "production"
title = "iambear.one"
description = "Collecting Memories"
keywords = [ "Blog", "Portfolio", "PaperMod" ]
author = "bear"
images = [ "<link or path of image for opengraph, twitter-cards>" ]
DateFormat = "January 2, 2006"
defaultTheme = "auto"
disableThemeToggle = true
ShowReadingTime = true
ShowShareButtons = false
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = true
ShowRssButtonInSectionTermList = false
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = false
tocopen = false

  [params.assets]
  favicon = "<link / abs url>"
  favicon16x16 = "<link / abs url>"
  favicon32x32 = "<link / abs url>"
  apple_touch_icon = "<link / abs url>"
  safari_pinned_tab = "<link / abs url>"

  [params.label]
  text = "iambear.one"
  icon = "/apple-touch-icon.png"
  iconHeight = 35

  [params.homeInfoParams]
  Title = "Hi there 👋"
  Content = "Here's my stuff"

  [params.cover]
  hidden = true
  hiddenInList = true
  hiddenInSingle = true

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  limit = 10
  keys = [ "title", "permalink", "summary", "content" ]

[[menu.main]]
identifier = "Posts"
name = "Posts"
url = "/categories/other"
weight = 10

[[menu.main]]
identifier = "Portfolio"
name = "Portfolio"
url = "/categories/portfolio"
weight = 20

[[menu.main]]
identifier = "Book Reviews"
name = "Book Reviews"
url = "/categories/book-reviews"
weight = 25

[[menu.main]]
identifier = "Archive"
name = "Archive"
url = "/archive/"
weight = 30

[[menu.main]]
identifier = "LinkedIn"
name = "LinkedIn"
url = "https://www.linkedin.com/in/iambearone/"
weight = 40

[[menu.main]]
identifier = "example"
name = "Reforge Artifacts"
url = "https://www.reforge.com/profiles/bjorn-seaton"
weight = 45

[markup.highlight]
noClasses = false

[params.profileMode]
enabled = true
title = "Hi there 👋"
subtitle = "Here's my stuff"

  [[params.profileMode.buttons]]
  name = "Posts"
  url = "/categories/other"

  [[params.profileMode.buttons]]
  name = "Portfolio"
  url = "/categories/portfolio"

  [[params.profileMode.buttons]]
  name = "Book Reviews"
  url = "/categories/book-reviews"
  
  [[params.profileMode.buttons]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/iambearone/"

  [[params.profileMode.buttons]]
  name = "Reforge Artifacts"
  url = "https://www.reforge.com/profiles/bjorn-seaton"

